const fs = require('fs');
const file = 'DevTrack/app/dashboard/page.tsx';
let content = fs.readFileSync(file, 'utf-8');

// 1. Añadir el estado showHint
content = content.replace(
  'const [showSolution, setShowSolution] = useState(false);',
  'const [showSolution, setShowSolution] = useState(false);\n  const [showHint, setShowHint] = useState(false);'
);

// 2. Limpiar el hint y solution al cambiar de tema
content = content.replace(
  'setShowSolution(false); \n                            }}',
  'setShowSolution(false); \n                              setShowHint(false);\n                            }}'
);
content = content.replace(
  'setShowSolution(false); }} className="absolute top-4',
  'setShowSolution(false); setShowHint(false); }} className="absolute top-4'
);
content = content.replace(
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false); }} className="w-16 h-16',
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false); setShowHint(false); }} className="w-16 h-16'
);
content = content.replace(
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false); }} className="bg-emerald',
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false); setShowHint(false); }} className="bg-emerald'
);
content = content.replace(
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false);',
  'setIsGaming(false); setIsCoding(false); setActiveTopic(0); setShowSolution(false); setShowHint(false);'
); // Catch any remaining

// 3. Reemplazar la UI de Soluciones/Hints
const oldUI = `                                {/* SISTEMA DE HONOR Y SOLUCIONES */}
                                {!showSolution ? (
                                  <button onClick={() => setShowSolution(true)} className="bg-emerald-500 hover:bg-emerald-400 text-white text-[10px] font-black uppercase tracking-widest px-4 py-3 rounded-xl transition-all w-full mt-6 shadow-lg shadow-emerald-500/20">
                                    👀 Ver Solución Esperada
                                  </button>
                                ) : (`;

const newUI = `                                {/* SISTEMA DE HONOR Y SOLUCIONES */}
                                {!showSolution ? (
                                  <div className="flex flex-col gap-3 mt-6">
                                    {!showHint ? (
                                      <button onClick={() => setShowHint(true)} className="bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/30 text-[10px] font-black uppercase tracking-widest px-4 py-3 rounded-xl transition-all w-full shadow-lg">
                                        💡 Mostrar Pista
                                      </button>
                                    ) : (
                                      <div className="bg-blue-900/20 border border-blue-500/30 p-5 rounded-xl animate-in fade-in zoom-in">
                                        <span className="text-[10px] font-black text-blue-400 uppercase tracking-widest block mb-2">💡 Pista del sistema</span>
                                        <p className="text-blue-100/80 text-[13px] font-medium whitespace-pre-wrap">{topic.hint}</p>
                                      </div>
                                    )}
                                    <button onClick={() => setShowSolution(true)} className="bg-emerald-500 hover:bg-emerald-400 text-white text-[10px] font-black uppercase tracking-widest px-4 py-3 rounded-xl transition-all w-full shadow-lg shadow-emerald-500/20">
                                      👀 Ver Solución Esperada
                                    </button>
                                  </div>
                                ) : (`;
content = content.replace(oldUI, newUI);

// 4. Reemplazar getCurriculum por una versión masiva con hints
const curriculumStart = content.indexOf('// CURRÍCULUM DINÁMICO PARA EL ENTRENAMIENTO EN CÓDIGO');
const curriculumEnd = content.indexOf('  // LÓGICA DEL MINI-JUEGO');

const massiveCurriculum = `// CURRÍCULUM DINÁMICO PARA EL ENTRENAMIENTO EN CÓDIGO
  const getCurriculum = (techName: string) => {
    const t = techName.toLowerCase();

    if (t.includes('python')) {
      return [
        { id: 'vars', title: '1. Variables y Tipos Dinámicos', explanation: 'En Python las variables no necesitan declarar su tipo (tipado dinámico). Usamos espacios (indentación) en lugar de llaves {} para definir bloques de código.', example: 'nombre = "Guido"\\nedad = 30\\n\\nif edad >= 18:\\n    print(nombre + " es mayor")', exercise: 'Crea una variable "puntuacion" con valor 100. Usa un condicional (if) para imprimir "Nivel superado" si es mayor o igual a 100.', hint: 'Usa "if puntuacion >= 100:" y no olvides los dos puntos al final.', solution: 'puntuacion = 100\\nif puntuacion >= 100:\\n    print("Nivel superado")' },
        { id: 'lists', title: '2. Estructuras de Datos: Listas y Diccionarios', explanation: 'Python usa Listas (mutables, ordenadas) y Diccionarios (pares clave-valor) como estructuras fundamentales.', example: 'juegos = ["Zelda", "Mario"]\\njuegos.append("Halo")\\n\\nperfil = {"nombre": "Alex", "nivel": 10}\\nprint(perfil["nivel"])', exercise: 'Crea un diccionario "personaje" con "clase" y "hp". Añade un hechizo nuevo a una lista de hechizos y muéstralos.', hint: 'Un diccionario usa llaves {} y una lista corchetes []. Añade a la lista con .append()', solution: 'personaje = {"clase": "Mago", "hp": 150}\\nhechizos = ["Fuego"]\\nhechizos.append("Hielo")\\nprint(personaje, hechizos)' },
        { id: 'comp', title: '3. List Comprehensions', explanation: 'Permite crear y filtrar listas en una sola línea. Es más rápido y idiomático en Python (Pythonic).', example: 'numeros = [1, 2, 3, 4, 5]\\ncuadrados = [n * n for n in numeros]\\npares = [n for n in numeros if n % 2 == 0]', exercise: 'Dada la lista nums = [1,2,3,4,5,6], crea una lista "mayores_que_tres" usando comprehension.', hint: 'Sintaxis: [elemento for elemento in lista if condicion]', solution: 'nums = [1, 2, 3, 4, 5, 6]\\nmayores_que_tres = [n for n in nums if n > 3]\\nprint(mayores_que_tres)' },
        { id: 'funcs', title: '4. Funciones y Argumentos (*args, **kwargs)', explanation: 'Las funciones se definen con "def". Puedes aceptar un número indeterminado de argumentos posicionales (*args) y nombrados (**kwargs).', example: 'def saludar(*nombres):\\n    for n in nombres:\\n        print("Hola", n)\\n\\nsaludar("Ana", "Juan", "Pedro")', exercise: 'Crea una función "promedio" que reciba *args y devuelva la suma de todos dividida por la cantidad de argumentos.', hint: 'Usa sum(args) para sumar y len(args) para contar. Asegúrate de evitar división por cero.', solution: 'def promedio(*args):\\n    if len(args) == 0: return 0\\n    return sum(args) / len(args)\\nprint(promedio(10, 20, 30))' },
        { id: 'oop', title: '5. POO: Clases y Herencia', explanation: 'Python soporta Programación Orientada a Objetos. El método __init__ es el constructor. La herencia se define pasando la clase base entre paréntesis.', example: 'class Animal:\\n    def hablar(self): pass\\n\\nclass Gato(Animal):\\n    def hablar(self):\\n        return "Miau"', exercise: 'Crea una clase "Arma" con atributo "dano". Crea "Espada" que herede de Arma y tenga un método "atacar".', hint: 'Usa def __init__(self, dano) en Arma. En Espada, hereda así: class Espada(Arma):', solution: 'class Arma:\\n    def __init__(self, dano):\\n        self.dano = dano\\n\\nclass Espada(Arma):\\n    def atacar(self):\\n        print(f"Atacas haciendo {self.dano} de daño!")\\n\\ne = Espada(50)\\ne.atacar()' },
        { id: 'decorators', title: '6. Decoradores (Avanzado)', explanation: 'Los decoradores modifican el comportamiento de una función o clase sin cambiar su código. Usan el símbolo @.', example: 'def log_decorator(func):\\n    def wrapper(*args, **kwargs):\\n        print("Llamando a la función")\\n        return func(*args, **kwargs)\\n    return wrapper\\n\\n@log_decorator\\ndef sumar(a, b): return a + b', exercise: 'Crea un decorador "duplicar_resultado" que tome la salida de la función decorada y la multiplique por 2.', hint: 'El wrapper debe hacer return func(*args, **kwargs) * 2', solution: 'def duplicar_resultado(func):\\n    def wrapper(*args, **kwargs):\\n        return func(*args, **kwargs) * 2\\n    return wrapper\\n\\n@duplicar_resultado\\ndef devolver_diez(): return 10\\n\\nprint(devolver_diez())' },
        { id: 'generators', title: '7. Generadores (Yield)', explanation: 'Los generadores devuelven iteradores que calculan valores perezosamente (lazy evaluation) ahorrando memoria. Usan la palabra clave yield en vez de return.', example: 'def contar_hasta(n):\\n    i = 1\\n    while i <= n:\\n        yield i\\n        i += 1\\n\\nfor num in contar_hasta(3): print(num)', exercise: 'Crea un generador "fibonacci" que devuelva los primeros N números de la secuencia.', hint: 'Usa a, b = b, a + b dentro de un bucle while y usa yield a.', solution: 'def fibonacci(n):\\n    a, b = 0, 1\\n    for _ in range(n):\\n        yield a\\n        a, b = b, a + b\\n\\nprint(list(fibonacci(5)))' },
        { id: 'context_mgr', title: '8. Context Managers (with)', explanation: 'La declaración with maneja recursos automáticamente (ej. cerrar archivos) usando los métodos __enter__ y __exit__ por debajo.', example: 'with open("archivo.txt", "w") as f:\\n    f.write("Hola")\\n# Se cierra automáticamente', exercise: 'Abre un archivo ficticio llamado "data.txt" en modo lectura ("r") usando with y lee su contenido.', hint: 'La sintaxis es: with open("data.txt", "r") as f: data = f.read()', solution: 'try:\\n    with open("data.txt", "r") as f:\\n        contenido = f.read()\\n        print(contenido)\\nexcept FileNotFoundError:\\n    print("No existe")' },
        { id: 'exceptions', title: '9. Manejo de Excepciones', explanation: 'Prevé y gestiona errores en ejecución mediante bloques try / except / else / finally para evitar cierres abruptos del programa.', example: 'try:\\n    res = 10 / 0\\nexcept ZeroDivisionError:\\n    print("Error")\\nfinally:\\n    print("Terminado")', exercise: 'Intenta convertir un string "abc" a entero. Captura el ValueError e imprime "No es un número".', hint: 'Usa int("abc") dentro de un try y except ValueError:', solution: 'try:\\n    n = int("abc")\\nexcept ValueError:\\n    print("No es un número")' },
        { id: 'dunder', title: '10. Magic Methods (Dunder)', explanation: 'Los métodos con doble guion bajo (__str__, __len__, __add__) permiten sobrecargar operadores estándar.', example: 'class Caja:\\n    def __init__(self, obj): self.obj = obj\\n    def __str__(self): return f"Caja[{self.obj}]"\\n\\nc = Caja(5)\\nprint(c) # Caja[5]', exercise: 'Crea una clase Vector con x e y. Sobrecarga el operador + (__add__) para sumar dos Vectores.', hint: 'def __add__(self, otro): return Vector(self.x + otro.x, self.y + otro.y)', solution: 'class Vector:\\n    def __init__(self, x, y):\\n        self.x, self.y = x, y\\n    def __add__(self, other):\\n        return Vector(self.x + other.x, self.y + other.y)\\n    def __str__(self):\\n        return f"({self.x}, {self.y})"\\n\\nv1 = Vector(1, 2)\\nv2 = Vector(3, 4)\\nprint(v1 + v2)' }
      ];
    }

    if (t.includes('react') || t.includes('next')) {
      return [
        { id: 'jsx', title: '1. Fundamentos de JSX', explanation: 'JSX es una extensión de sintaxis para JavaScript que se asemeja a HTML. Los atributos usan camelCase (ej. className en lugar de class).', example: 'export default function Titulo() {\\n  return <h1 className="text-xl">Hola</h1>;\\n}', exercise: 'Crea un componente "Boton" que reciba texto en una variable e imprima un <button> con la clase "btn-primary".', hint: 'Recuerda usar className="btn-primary" y llaves {} para inyectar la variable de texto.', solution: 'export default function Boton() {\\n  const texto = "Enviar";\\n  return <button className="btn-primary">{texto}</button>;\\n}' },
        { id: 'state', title: '2. Manejo de Estado (useState)', explanation: 'useState permite añadir variables de estado a los componentes funcionales. Cuando el estado cambia, el componente se re-renderiza.', example: 'import { useState } from "react";\\n\\nexport default function Contador() {\\n  const [count, setCount] = useState(0);\\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\\n}', exercise: 'Crea un componente con un estado "encendido" (booleano). Un botón debe alternar su valor.', hint: 'Usa setEncendido(!encendido) en el onClick.', solution: 'import { useState } from "react";\\nexport default function Interruptor() {\\n  const [encendido, setEncendido] = useState(false);\\n  return (\\n    <button onClick={() => setEncendido(!encendido)}>\\n      {encendido ? "On" : "Off"}\\n    </button>\\n  );\\n}' },
        { id: 'props', title: '3. Propiedades (Props)', explanation: 'Las Props permiten pasar datos unidireccionalmente (de padre a hijo). Promueven la reutilización de componentes.', example: 'function Usuario({ nombre }) {\\n  return <div>{nombre}</div>;\\n}\\n\\nexport default function App() {\\n  return <Usuario nombre="Alex" />;\\n}', exercise: 'Crea un componente "Perfil" que reciba "avatarUrl" y "username" como props. Renderízalo en un App padre.', hint: 'Desestructura { avatarUrl, username } en los argumentos de la función Perfil.', solution: 'function Perfil({ avatarUrl, username }) {\\n  return (\\n    <div>\\n      <img src={avatarUrl} alt={username} />\\n      <span>{username}</span>\\n    </div>\\n  );\\n}\\nexport default function App() {\\n  return <Perfil avatarUrl="/img.png" username="Alex" />;\\n}' },
        { id: 'effect', title: '4. Efectos Secundarios (useEffect)', explanation: 'useEffect sincroniza el componente con sistemas externos (APIs, timers, DOM). El array de dependencias controla cuándo se ejecuta.', example: 'import { useEffect, useState } from "react";\\n\\nexport default function Timer() {\\n  useEffect(() => {\\n    console.log("Montado");\\n  }, []);\\n  return <div>Hola</div>;\\n}', exercise: 'Usa useEffect para actualizar el document.title con la cantidad de clicks de un estado contador.', hint: 'El array de dependencias de useEffect debe ser [clicks] para que se ejecute solo cuando cambie el estado.', solution: 'import { useState, useEffect } from "react";\\nexport default function Clicks() {\\n  const [clicks, setClicks] = useState(0);\\n  useEffect(() => {\\n    document.title = "Clicks: " + clicks;\\n  }, [clicks]);\\n  return <button onClick={() => setClicks(c => c+1)}>+1</button>;\\n}' },
        { id: 'context', title: '5. Context API (Estado Global)', explanation: 'Context evita el "prop drilling" (pasar props a través de muchos niveles). Ideal para temas (dark/light).', example: 'import { createContext, useContext } from "react";\\nconst ThemeContext = createContext("light");\\n\\nfunction Texto() {\\n  const theme = useContext(ThemeContext);\\n  return <p>{theme}</p>;\\n}', exercise: 'Crea un UserContext. Provee un objeto {name: "Dev"} y consúmelo en un componente hijo.', hint: 'Usa UserContext.Provider con la prop value y envuelve el componente hijo.', solution: 'import { createContext, useContext } from "react";\\nconst UserContext = createContext(null);\\n\\nfunction Hijo() {\\n  const user = useContext(UserContext);\\n  return <h1>Hola {user.name}</h1>;\\n}\\n\\nexport default function App() {\\n  return (\\n    <UserContext.Provider value={{name: "Dev"}}>\\n      <Hijo />\\n    </UserContext.Provider>\\n  );\\n}' },
        { id: 'refs', title: '6. Referencias al DOM (useRef)', explanation: 'useRef permite almacenar un valor mutable que NO provoca re-renderizados cuando se actualiza. Sirve también para referenciar elementos del DOM.', example: 'import { useRef } from "react";\\n\\nexport default function App() {\\n  const inputRef = useRef(null);\\n  return <input ref={inputRef} />;\\n}', exercise: 'Crea un input y un botón que, al hacerle click, ponga el foco (focus()) en el input usando useRef.', hint: 'Llama a inputRef.current.focus() en la función del botón.', solution: 'import { useRef } from "react";\\nexport default function FocusApp() {\\n  const inputRef = useRef(null);\\n  return (\\n    <>\\n      <input ref={inputRef} />\\n      <button onClick={() => inputRef.current.focus()}>Enfocar</button>\\n    </>\\n  );\\n}' },
        { id: 'memo', title: '7. Optimización (useMemo y useCallback)', explanation: 'Evita cálculos costosos en cada render con useMemo, o la recreación de funciones con useCallback.', example: 'const calcCostoso = useMemo(() => computar(data), [data]);\\nconst memoizedFn = useCallback(() => hacerAlgo(), []);', exercise: 'Usa useMemo para filtrar un array enorme de números y quedarte solo con los pares, dependiendo del array "nums".', hint: 'const pares = useMemo(() => nums.filter(n => n % 2 === 0), [nums]);', solution: 'import { useMemo } from "react";\\nexport default function OptApp({ nums }) {\\n  const pares = useMemo(() => nums.filter(n => n % 2 === 0), [nums]);\\n  return <div>{pares.length} pares</div>;\\n}' },
        { id: 'customhooks', title: '8. Custom Hooks', explanation: 'Puedes extraer lógica de estado a tus propios Hooks (funciones que empiezan por "use") para reutilizarlos en otros componentes.', example: 'function useToggle(initial = false) {\\n  const [v, setV] = useState(initial);\\n  const toggle = () => setV(!v);\\n  return [v, toggle];\\n}', exercise: 'Crea un custom hook "useCounter" que maneje un número y devuelva [count, increment]. Úsalo en un componente.', hint: 'El custom hook usa useState internamente y retorna un array [estado, funcion].', solution: 'import { useState } from "react";\\nfunction useCounter(initial = 0) {\\n  const [count, setCount] = useState(initial);\\n  const increment = () => setCount(c => c + 1);\\n  return [count, increment];\\n}\\nexport default function App() {\\n  const [c, inc] = useCounter(10);\\n  return <button onClick={inc}>{c}</button>;\\n}' }
      ];
    }

    if (t.includes('javascript') || t.includes('typescript') || t.includes('node') || t.includes('express')) {
      return [
        { id: 'letconst', title: '1. Variables y Scopes (ES6+)', explanation: 'Usa const por defecto para variables inmutables en referencia. Usa let para valores que van a ser reasignados.', example: 'const API = "api.com";\\nlet reintentos = 0;', exercise: 'Crea una constante para un IVA (0.21) y una variable "precio" usando let. Calcula el total.', hint: 'Total es igual a precio + precio * IVA', solution: 'const IVA = 0.21;\\nlet precio = 100;\\nlet total = precio + (precio * IVA);\\nconsole.log(total);' },
        { id: 'arrow', title: '2. Arrow Functions y This', explanation: 'Las funciones flecha proveen una sintaxis concisa y no tienen su propio this.', example: 'const duplicar = (num) => num * 2;', exercise: 'Crea una función flecha saludar que reciba un nombre y retorne un template string.', hint: 'Usa backticks (comillas invertidas)', solution: 'const saludar = (nombre) => "Hola " + nombre;\\nconsole.log(saludar("Dev"));' },
        { id: 'arraymeth', title: '3. Programación Funcional: Arrays', explanation: 'Métodos inmutables como map(), filter(), y reduce() son esenciales para transformar datos de forma declarativa.', example: 'const aprobados = notas.filter(n => n >= 5);', exercise: 'Usa reduce() para sumar un array de precios: [10, 20, 30].', hint: 'El acumulador y el valor actual se suman, iniciando el acumulador en 0.', solution: 'const precios = [10, 20, 30];\\nconst total = precios.reduce((acc, val) => acc + val, 0);\\nconsole.log(total);' },
        { id: 'destruct', title: '4. Desestructuración y Spread', explanation: 'Desestructurar extrae valores. Spread (...) copia objetos o arrays.', example: 'const { rol } = user;\\nconst copia = { ...user };', exercise: 'Desestructura la propiedad email de un objeto. Crea una copia usando spread añadiendo la propiedad token.', hint: 'const { email } = obj; const nuevo = { ...obj, token: "abc" };', solution: 'const o = { email: "a@a.com" };\\nconst { email } = o;\\nconst nuevo = { ...o, token: "123" };\\nconsole.log(email, nuevo);' },
        { id: 'async', title: '5. Asincronía: Promises y Async/Await', explanation: 'JavaScript es Single-Thread. Las promesas y async/await manejan operaciones asíncronas sin bloquear el hilo.', example: 'async function fetchUser() {\\n  const res = await fetch("/api");\\n  return res.json();\\n}', exercise: 'Escribe una función asíncrona que espere 1 segundo usando setTimeout y Promesa y luego imprima "Listo".', hint: 'Envuelve setTimeout en new Promise(resolve => setTimeout(resolve, 1000))', solution: 'const delay = (ms) => new Promise(res => setTimeout(res, ms));\\nasync function esperar() {\\n  await delay(1000);\\n  console.log("Listo");\\n}\\nesperar();' },
        { id: 'ts_types', title: '6. (TypeScript) Tipos e Interfaces', explanation: 'TypeScript añade tipado estático opcional. interface y type definen la forma de los objetos.', example: 'interface Producto {\\n  id: number;\\n  precio?: number; // Opcional\\n}', exercise: 'Define una interfaz Jugador con alias (string) y nivel (number). Crea una variable de ese tipo.', hint: 'Usa "interface" para definirlo y asócialo con ":" al declarar la variable.', solution: 'interface Jugador {\\n  alias: string;\\n  nivel: number;\\n}\\nconst j: Jugador = { alias: "Hero", nivel: 5 };' },
        { id: 'ts_generics', title: '7. (TypeScript) Genéricos', explanation: 'Los tipos genéricos permiten crear componentes reutilizables que funcionan con varios tipos de datos en vez de uno solo.', example: 'function ident<T>(arg: T): T {\\n  return arg;\\n}', exercise: 'Crea una interfaz de clase "RespuestaAPI<T>" que tenga una propiedad data de tipo T y un boolean success.', hint: 'interface RespuestaAPI<T> { data: T; success: boolean; }', solution: 'interface RespuestaAPI<T> {\\n  data: T;\\n  success: boolean;\\n}\\nconst res: RespuestaAPI<string> = { data: "Ok", success: true };' },
        { id: 'oop_js', title: '8. Clases (ES6)', explanation: 'JavaScript tiene soporte para Programación Orientada a Objetos mediante sintaxis de clases (sugar sintax de prototipos).', example: 'class Animal {\\n  constructor(n) { this.nombre = n; }\\n}', exercise: 'Crea una clase Vehiculo con método "arrancar" e implementa una subclase Moto.', hint: 'Usa class Moto extends Vehiculo y llama a super() en el constructor si es necesario.', solution: 'class Vehiculo {\\n  arrancar() { console.log("Brum"); }\\n}\\nclass Moto extends Vehiculo {\\n  caballito() { console.log("Yeehaw!"); }\\n}\\nnew Moto().arrancar();' },
        { id: 'modules', title: '9. Módulos ES (Import/Export)', explanation: 'Separa tu código en múltiples archivos. Usa export (nombrado o default) y luego import.', example: 'export const PI = 3.14;\\nexport default function app() {}', exercise: 'Escribe la sintaxis para exportar por defecto una función "calcular" y luego importarla en otro archivo ficticio.', hint: 'export default function calcular()... import calcular from "./archivo.js"', solution: '// file1.js\\nexport default function calcular() {}\\n\\n// file2.js\\nimport calcular from "./file1.js";' },
        { id: 'eventloop', title: '10. Event Loop y Callbacks', explanation: 'JavaScript procesa tareas de forma no bloqueante mediante un Event Loop (Microtasks y Macrotasks).', example: 'setTimeout(() => console.log("A"), 0);\\nPromise.resolve().then(() => console.log("B"));\\n// Orden: B, A', exercise: 'Intenta predecir el orden de impresión de: un console.log síncrono, una promesa resuelta y un setTimeout.', hint: 'Lo síncrono va primero. Luego las microtareas (promesas). Por último las macrotareas (setTimeout).', solution: 'console.log("1"); // Síncrono\\nsetTimeout(() => console.log("3"), 0); // Macrotask\\nPromise.resolve().then(() => console.log("2")); // Microtask' }
      ];
    }

    if (t.includes('java') || t.includes('c#')) {
      let isCSharp = t.includes('c#') || t.includes('csharp');
      let print = isCSharp ? 'Console.WriteLine' : 'System.out.println';
      let title = isCSharp ? 'C#' : 'Java';
      return [
        { id: 'types', title: "1. Fundamentos de " + title, explanation: "Lenguaje de tipado estricto. Las variables exigen declaración de tipo. Todo debe estar dentro de clases.", example: 'public class Main {\\n  public static void main(String[] args) {\\n    int edad = 25;\\n    String nombre = "Alex";\\n    ' + print + '("Hola " + nombre);\\n  }\\n}', exercise: 'Declara una variable flotante para un precio e imprímelo.', hint: 'Usa float o double.', solution: 'double precio = 99.99;\\nString prod = "Teclado";\\n' + print + '(prod + ": " + precio);' },
        { id: 'oop_encap', title: '2. Clases y Encapsulamiento', explanation: 'El encapsulamiento oculta el estado interno (private) y expone métodos públicos (Getters/Setters).', example: 'class Cuenta {\\n  private double saldo;\\n  public double getSaldo() { return saldo; }\\n}', exercise: 'Crea una clase Guerrero con variable privada energia. Crea un método que le reste a la energía.', hint: 'Haz un método public void gastarEnergia(int e) { energia -= e; }', solution: 'class Guerrero {\\n  private int energia = 100;\\n  public void gastarEnergia(int e) { energia -= e; }\\n  public int getEnergia() { return energia; }\\n}' },
        { id: 'interfaces', title: '3. Polimorfismo e Interfaces', explanation: 'Las interfaces definen un contrato (métodos sin cuerpo).', example: isCSharp ? 'interface IVolador { void Volar(); }' : 'interface Volador { void volar(); }', exercise: "Crea una interfaz Atacable y úsala en una clase Enemigo.", hint: 'Usa implements en Java o : en C# para implementar la interfaz.', solution: isCSharp ? 'interface IAtacable { void recibirDano(int d); }\\nclass Enemigo : IAtacable {\\n  public void recibirDano(int d) { Console.WriteLine("Daño: " + d); }\\n}' : 'interface Atacable { void recibirDano(int d); }\\nclass Enemigo implements Atacable {\\n  public void recibirDano(int d) { System.out.println("Daño: " + d); }\\n}' },
        { id: 'collections', title: '4. Colecciones Avanzadas', explanation: 'Usa estructuras dinámicas (List, Dictionary/Map, HashSet). Proveen mejor rendimiento y métodos integrados.', example: isCSharp ? 'var edades = new Dictionary<string, int>();' : 'Map<String, Integer> edades = new HashMap<>();', exercise: 'Crea un diccionario/map que guarde strings e integers e inserta un valor.', hint: 'Usa Add(clave, valor) en C# o put(clave, valor) en Java.', solution: isCSharp ? 'var stock = new Dictionary<string, int>();\\nstock.Add("A01", 50);\\nConsole.WriteLine(stock["A01"]);' : 'Map<String, Integer> stock = new HashMap<>();\\nstock.put("A01", 50);\\nSystem.out.println(stock.get("A01"));' },
        { id: 'linq_streams', title: isCSharp ? '5. LINQ (Consultas)' : '5. Streams (Programación Funcional)', explanation: isCSharp ? 'LINQ permite consultar colecciones como si fuera SQL.' : 'Los Streams en Java procesan colecciones de forma funcional y declarativa.', example: isCSharp ? 'var pares = nums.Where(n => n % 2 == 0).ToList();' : 'List<Integer> pares = nums.stream().filter(n -> n % 2 == 0).collect(Collectors.toList());', exercise: 'Filtra una lista de números para quedarte solo con los mayores a 10.', hint: 'Usa x => x > 10 en LINQ, o n -> n > 10 en Java Streams filter().', solution: isCSharp ? 'var mayores = lista.Where(x => x > 10).ToList();' : 'List<Integer> may = lista.stream().filter(x -> x > 10).collect(Collectors.toList());' },
        { id: 'generics', title: '6. Genéricos (Generics)', explanation: 'Los genéricos permiten escribir código fuerte y seguro que puede procesar múltiples tipos de objetos.', example: isCSharp ? 'class Caja<T> { public T Contenido { get; set; } }' : 'class Caja<T> { public T contenido; }', exercise: 'Crea una clase genérica que envuelva un valor de tipo T y un método para obtenerlo.', hint: 'Define la clase con <T> y el atributo de tipo T.', solution: 'class Contenedor<T> {\\n  private T dato;\\n  public Contenedor(T d) { dato = d; }\\n  public T getDato() { return dato; }\\n}' },
        { id: 'exceptions', title: '7. Manejo de Excepciones', explanation: 'Utiliza try, catch, finally (o using/try-with-resources) para gestionar errores de ejecución sin que el programa colapse.', example: 'try { int x = 10/0; } catch (Exception e) { ' + print + '("Error"); }', exercise: 'Escribe un bloque que intente acceder al índice 10 de un array de 2 elementos y atrape el error.', hint: 'Atrapa la excepción IndexOutOfBoundsException en Java o IndexOutOfRangeException en C#.', solution: 'try {\\n  int[] arr = {1, 2};\\n  int val = arr[10];\\n} catch (Exception e) {\\n  ' + print + '("Índice incorrecto");\\n}' },
        { id: 'concurrency', title: '8. Concurrencia y Async', explanation: 'Para tareas pesadas, se usan hilos (Threads) o patrones Async/Await (C#) / CompletableFuture (Java).', example: isCSharp ? 'async Task DoWork() { await Task.Delay(1000); }' : 'CompletableFuture.runAsync(() -> doWork());', exercise: 'Realiza un código mínimo que simule una tarea asíncrona de impresión de consola.', hint: 'Si es C# usa async Task. Si es Java puedes usar hilos (new Thread( () -> ...).start()).', solution: isCSharp ? 'async Task Tarea() {\\n  await Task.Delay(500);\\n  Console.WriteLine("Listo");\\n}' : 'new Thread(() -> {\\n  System.out.println("Listo en otro hilo");\\n}).start();' }
      ];
    }

    if (t.includes('c++') || t.includes('cpp') || t === 'c') {
      return [
        { id: 'headers', title: '1. Sintaxis Básica y Memoria', explanation: 'C++ requiere inclusión de librerías (<iostream>). Te da un control de bajo nivel pero exige gestionar la memoria rigurosamente.', example: '#include <iostream>\\nusing namespace std;\\n\\nint main() {\\n  cout << "Iniciando..." << endl;\\n  return 0;\\n}', exercise: 'Escribe un programa mínimo en C++ que pida entrada std::cin de un número y lo imprima.', hint: 'Recuerda usar #include <iostream>, declarar la variable int y usar cin >> var.', solution: '#include <iostream>\\nusing namespace std;\\nint main() {\\n  int n;\\n  cin >> n;\\n  cout << n << endl;\\n  return 0;\\n}' },
        { id: 'pointers', title: '2. Punteros y Referencias', explanation: 'Un puntero (*) almacena la dirección de memoria. Una referencia (&) es un alias de una variable.', example: 'void incrementar(int& valor) {\\n  valor++;\\n}\\nint main() { int v = 10; incrementar(v); }', exercise: 'Escribe una función doblarDano que reciba un puntero a int y multiplique su valor por 2.', hint: 'El parámetro debe ser int* d, y dentro usas *d = *d * 2.', solution: 'void doblarDano(int* d) {\\n  *d *= 2;\\n}' },
        { id: 'vectors', title: '3. STL: std::vector', explanation: 'La Standard Template Library provee contenedores de datos. std::vector es el array dinámico.', example: '#include <vector>\\nvector<int> puntos = {10, 20};\\npuntos.push_back(30);', exercise: 'Itera sobre un vector de strings conteniendo nombres usando un range-based for.', hint: 'for(const string& nombre : nombres) { ... }', solution: 'vector<string> nombres = {"A", "B"};\\nfor(const string& n : nombres) {\\n  cout << n << endl;\\n}' },
        { id: 'oop_cpp', title: '4. Clases, RAII y Destructores', explanation: 'RAII (Resource Acquisition Is Initialization). Los recursos se adquieren en el constructor y se liberan en el destructor (~).', example: 'class Conexion {\\npublic:\\n  Conexion() { cout << "Abierta"; }\\n  ~Conexion() { cout << "Cerrada"; }\\n};', exercise: 'Crea una clase Archivo con constructor y destructor que impriman "Abrir" y "Cerrar".', hint: 'El destructor se nombra igual que la clase precedido por el símbolo tilde ~.', solution: 'class Archivo {\\npublic:\\n  Archivo() { cout << "Abrir"; }\\n  ~Archivo() { cout << "Cerrar"; }\\n};' },
        { id: 'smart_ptr', title: '5. Punteros Inteligentes (C++11)', explanation: 'No uses raw pointers (new/delete). Usa std::unique_ptr para evitar fugas de memoria.', example: '#include <memory>\\nstd::unique_ptr<int> j = std::make_unique<int>(10);', exercise: 'Instancia un entero dinámico usando std::unique_ptr<int> y std::make_unique.', hint: 'Usa auto ptr = std::make_unique<int>(valor);', solution: '#include <memory>\\nint main() {\\n  auto numero = std::make_unique<int>(42);\\n  return 0;\\n}' },
        { id: 'templates', title: '6. Templates (Plantillas)', explanation: 'Las plantillas permiten crear funciones y clases genéricas, similares a los Generics en Java/C# pero resueltas en tiempo de compilación.', example: 'template <typename T>\\nT sumar(T a, T b) { return a + b; }', exercise: 'Crea una función template "maximo" que reciba dos parámetros de tipo T y devuelva el mayor.', hint: 'Usa el operador ternario: return (a > b) ? a : b;', solution: 'template <typename T>\\nT maximo(T a, T b) {\\n  return (a > b) ? a : b;\\n}' },
        { id: 'lambdas', title: '7. Funciones Lambda', explanation: 'Desde C++11 existen lambdas (cierres) que pueden capturar variables del entorno.', example: 'int offset = 10;\\nauto fn = [offset](int val) { return val + offset; };', exercise: 'Crea una lambda que capture una variable externa "multiplicador" por referencia [&] y la altere.', hint: 'auto miLambda = [&multiplicador]() { multiplicador *= 2; };', solution: 'int m = 5;\\nauto doblar = [&m]() { m *= 2; };\\ndoblar();\\ncout << m; // 10' }
      ];
    }
    
    if (t.includes('sql') || t.includes('database')) {
      return [
        { id: 'select', title: '1. Consultas Básicas (SELECT)', explanation: 'SELECT obtiene datos de una tabla. Puedes filtrar con WHERE.', example: 'SELECT nombre FROM usuarios WHERE edad > 18;', exercise: 'Selecciona el email de todos los usuarios cuyo rol sea "admin".', hint: 'Usa WHERE rol = \\\'admin\\\'', solution: 'SELECT email FROM users WHERE rol = \\\'admin\\\';' },
        { id: 'join', title: '2. Uniones (JOIN)', explanation: 'JOIN combina filas de dos o más tablas basándose en una columna común.', example: 'SELECT a.nombre, b.ciudad FROM users a JOIN ciudades b ON a.city_id = b.id;', exercise: 'Une una tabla empleados con departamentos usando el departamento_id.', hint: 'INNER JOIN departamentos ON empleados.departamento_id = departamentos.id', solution: 'SELECT empleados.nombre, departamentos.nombre \\nFROM empleados \\nINNER JOIN departamentos ON empleados.departamento_id = departamentos.id;' },
        { id: 'aggr', title: '3. Funciones de Agregación', explanation: 'COUNT(), SUM(), AVG(), MAX() y MIN() calculan valores a partir de múltiples filas.', example: 'SELECT categoria, SUM(ventas) FROM productos GROUP BY categoria;', exercise: 'Calcula el promedio (AVG) del salario en la tabla nomina.', hint: 'SELECT AVG(columna) FROM tabla', solution: 'SELECT AVG(salario) FROM nomina;' },
        { id: 'subq', title: '4. Subconsultas (Subqueries)', explanation: 'Una consulta anidada dentro de otra, generalmente dentro de una cláusula WHERE, HAVING o FROM.', example: 'SELECT nombre FROM empleados WHERE salario > (SELECT AVG(salario) FROM empleados);', exercise: 'Encuentra los nombres de productos cuyo precio sea mayor al máximo precio de la categoría 1.', hint: 'Usa WHERE precio > (SELECT MAX(precio) FROM productos WHERE categoria = 1)', solution: 'SELECT nombre FROM productos \\nWHERE precio > (SELECT MAX(precio) FROM productos WHERE categoria = 1);' },
        { id: 'indexes', title: '5. Índices (Performance)', explanation: 'Los índices aceleran enormemente las consultas de lectura a costa de tiempo de inserción y espacio.', example: 'CREATE INDEX idx_user_email ON users(email);', exercise: 'Crea un índice en la columna "fecha_registro" de la tabla "pagos".', hint: 'CREATE INDEX nombre_indice ON tabla(columna);', solution: 'CREATE INDEX idx_pagos_fecha ON pagos(fecha_registro);' }
      ];
    }

    if (t.includes('rust')) {
      return [
        { id: 'ownership', title: '1. Propiedad (Ownership)', explanation: 'Rust gestiona la memoria a través de Ownership. Cada valor tiene un único "dueño". Si el dueño sale de ámbito, el valor se descarta.', example: 'let s1 = String::from("hola");\\nlet s2 = s1; // Movimiento (s1 ya no es válida)', exercise: 'Crea un String, asígnala a otra variable e intenta usar la primera variable para ver por qué falla (move).', hint: 'En Rust las cadenas se "mueven", no se copian por defecto a menos que uses .clone().', solution: 'let a = String::from("Rust");\\nlet b = a;\\n// println!("{}", a); // Da error de compilación' },
        { id: 'borrowing', title: '2. Préstamos (Borrowing)', explanation: 'Para usar un valor sin tomar propiedad, usamos referencias (&). Pueden ser inmutables (&T) o mutables (&mut T).', example: 'fn calc(s: &String) -> usize { s.len() }\\nlet s1 = String::from("hola");\\nlet len = calc(&s1);', exercise: 'Pasa una referencia de un String a una función e imprime su valor sin moverlo.', hint: 'La función debe aceptar (s: &String) y debes llamarla con &tu_string.', solution: 'fn print_str(s: &String) { println!("{}", s); }\\nfn main() {\\n  let msg = String::from("Hi");\\n  print_str(&msg);\\n}' },
        { id: 'enums', title: '3. Enums y Pattern Matching', explanation: 'Los enums en Rust pueden contener datos. match obliga a manejar todos los casos posibles.', example: 'enum Estado { Jugando, Puntaje(u32) }\\nlet st = Estado::Puntaje(100);\\nmatch st { ... }', exercise: 'Crea un Enum Mensaje con la variante Texto(String). Usa match para imprimirlo.', hint: 'match m { Mensaje::Texto(t) => println!("{}", t) }', solution: 'enum Mensaje { Texto(String) }\\nfn main() {\\n  let m = Mensaje::Texto(String::from("A"));\\n  match m {\\n    Mensaje::Texto(t) => println!("{}", t)\\n  }\\n}' },
        { id: 'structs', title: '4. Structs y Métodos (impl)', explanation: 'Las estructuras agrupan datos. El bloque impl asocia métodos y funciones a esa estructura.', example: 'struct Rect { w: u32, h: u32 }\\nimpl Rect { fn area(&self) -> u32 { self.w * self.h } }', exercise: 'Crea un Struct "Jugador" con "nombre" (String) y "hp" (u32). Añádele un método "esta_vivo" que retorne bool si hp > 0.', hint: 'Usa impl Jugador { fn esta_vivo(&self) -> bool { ... } }', solution: 'struct Jugador { nombre: String, hp: u32 }\\nimpl Jugador {\\n  fn esta_vivo(&self) -> bool {\\n    self.hp > 0\\n  }\\n}' },
        { id: 'error_handling', title: '5. Result y Option (Manejo de Errores)', explanation: 'Rust no usa excepciones. Usa los enums Option (para ausencia de valor) y Result (para operaciones fallidas).', example: 'fn dividir(a: f64, b: f64) -> Result<f64, String> {\\n  if b == 0.0 { Err("Div 0".to_string()) } else { Ok(a/b) }\\n}', exercise: 'Escribe una función que retorne Option<i32>. Si recibe true, retorna Some(10). Si es false, retorna None.', hint: 'Option tiene dos variantes: Some(valor) y None.', solution: 'fn obtener_numero(existe: bool) -> Option<i32> {\\n  if existe { Some(10) } else { None }\\n}' },
        { id: 'traits', title: '6. Traits (Rasgos)', explanation: 'Los Traits son análogos a las interfaces; definen un comportamiento que los tipos pueden implementar.', example: 'trait Describible { fn describir(&self) -> String; }\\nimpl Describible for Jugador { ... }', exercise: 'Crea un trait "Resumible" con un método "resumen(&self) -> String". Implementalo para cualquier struct.', hint: 'Sintaxis: impl Resumible for MiStruct { fn resumen(&self) -> String { ... } }', solution: 'trait Resumible { fn resumen(&self) -> String; }\\nstruct Libro { titulo: String }\\nimpl Resumible for Libro {\\n  fn resumen(&self) -> String { self.titulo.clone() }\\n}' }
      ];
    }

    if (t.includes('go') || t.includes('golang')) {
      return [
        { id: 'basics', title: '1. Variables y Tipos Básicos', explanation: 'Go es estáticamente tipado y compilado. Usa el operador := para declaración corta con inferencia de tipo.', example: 'var completo bool = true\\ncorto := "Hola Go" // Infiere string', exercise: 'Declara una variable entera usando var y otra usando := e imprímelas usando fmt.Println.', hint: 'Usa import "fmt". fmt.Println(v1, v2).', solution: 'package main\\nimport "fmt"\\nfunc main() {\\n  var a int = 1\\n  b := 2\\n  fmt.Println(a, b)\\n}' },
        { id: 'structs', title: '2. Structs y Punteros', explanation: 'Go no tiene clases. Usa Structs para objetos. Pasa punteros a funciones para mutar el objeto original.', example: 'type User struct { Name string }\\nfunc rename(u *User) { u.Name = "Bob" }', exercise: 'Crea un struct "Car" con un string Model. Haz una función que reciba un puntero a Car y cambie su modelo.', hint: 'La función recibe (c *Car).', solution: 'type Car struct { Model string }\\nfunc upgrade(c *Car) { c.Model = "Pro" }' },
        { id: 'goroutines', title: '3. Goroutines y Concurrencia', explanation: 'Goroutines son hilos ultra ligeros manejados por el runtime de Go. Se inician con la palabra clave "go".', example: 'go func() { fmt.Println("Async") }()', exercise: 'Llama asíncronamente a una función sayHello usando una goroutine y espera un momento con time.Sleep.', hint: 'Usa "go sayHello()". El paquete time sirve para Sleep.', solution: 'package main\\nimport ("fmt"; "time")\\nfunc main() {\\n  go func() { fmt.Println("Hola") }()\\n  time.Sleep(time.Second)\\n}' },
        { id: 'channels', title: '4. Channels (Canales)', explanation: 'Los Channels permiten a las Goroutines comunicarse entre sí sincronizadamente.', example: 'ch := make(chan int)\\ngo func() { ch <- 42 }()\\nval := <-ch', exercise: 'Crea un canal de strings, envía "Mensaje" asíncronamente y recíbelo en el main thread.', hint: 'Usa make(chan string). Envía con chan <- "Texto" y recibe con var = <- chan.', solution: 'package main\\nimport "fmt"\\nfunc main() {\\n  c := make(chan string)\\n  go func() { c <- "Ping" }()\\n  fmt.Println(<-c)\\n}' },
        { id: 'interfaces', title: '5. Interfaces Implícitas', explanation: 'Las interfaces en Go se implementan implícitamente, sin usar la palabra "implements". Si un tipo tiene los métodos de la interfaz, la implementa automáticamente.', example: 'type Speaker interface { Speak() }\\ntype Dog struct{}\\nfunc (d Dog) Speak() { fmt.Println("Woof") }', exercise: 'Crea una interfaz "Describer" con Describe() string, y un struct que cumpla con dicha interfaz.', hint: 'Simplemente crea un método de receptor (receiver) que coincida con la firma en la interfaz.', solution: 'type Desc interface { Describe() string }\\ntype Item struct{ id int }\\nfunc (i Item) Describe() string { return "Item" }' }
      ];
    }
    
    if (t.includes('php')) {
      return [
        { id: 'vars', title: '1. Variables y Arrays', explanation: 'En PHP todas las variables empiezan con $ y son débilmente tipadas. Los Arrays pueden ser asociativos (diccionarios).', example: '$edad = 30;\\n$user = ["nombre" => "Juan", "rol" => "Admin"];\\necho $user["nombre"];', exercise: 'Crea una variable $precio. Luego un if que imprima "Caro" si es mayor a 100, y "Barato" en caso contrario.', hint: 'Las variables siempre llevan $. Usa echo para imprimir.', solution: '$precio = 150;\\nif ($precio > 100) {\\n  echo "Caro";\\n} else {\\n  echo "Barato";\\n}' },
        { id: 'functions', title: '2. Funciones y Tipado Estricto', explanation: 'PHP moderno permite declaración de tipos para parámetros y retornos.', example: 'function sumar(int $a, int $b): int {\\n  return $a + $b;\\n}', exercise: 'Crea una función llamada calcularArea que reciba un entero $lado y retorne un entero con el área ($lado*$lado).', hint: 'Usa int para los argumentos y el tipo de retorno.', solution: 'function calcularArea(int $lado): int {\\n  return $lado * $lado;\\n}' },
        { id: 'oop_php', title: '3. Programación Orientada a Objetos', explanation: 'Soporta clases completas, herencia, interfaces, namespaces e inyección de dependencias.', example: 'class Perro {\\n  public string $nombre;\\n  public function __construct(string $n) {\\n    $this->nombre = $n;\\n  }\\n}', exercise: 'Crea una clase Vehiculo con atributo protegido $ruedas, y un constructor que asigne su valor.', hint: 'Usa __construct para inicializar el objeto y $this->ruedas para el scope interno.', solution: 'class Vehiculo {\\n  protected int $ruedas;\\n  public function __construct(int $r) {\\n    $this->ruedas = $r;\\n  }\\n}' }
      ];
    }

    if (t.includes('ruby')) {
      return [
        { id: 'vars', title: '1. Variables e Interpolación', explanation: 'Ruby es 100% orientado a objetos y con sintaxis amigable. No usa punto y coma.', example: 'nombre = "Mundo"\\nputs "Hola " + nombre', exercise: 'Declara una variable "vida" con valor 100. Imprime por pantalla: "Te queda X de vida".', hint: 'Usa puts para imprimir y concatena usando + vida.to_s', solution: 'vida = 100\\nputs "Te queda " + vida.to_s + " de vida"' },
        { id: 'blocks', title: '2. Bloques y Enumeradores', explanation: 'Los bloques (codigo entre do/end o {/}) son fundamentales en Ruby para iterar colecciones y callbacks.', example: '5.times do |i|\\n  puts "Iteración " + i.to_s\\nend', exercise: 'Usa el método .each en un array [10, 20] para imprimir cada valor por separado.', hint: 'array.each do |elemento| puts elemento end', solution: '[10, 20].each do |num|\\n  puts num\\nend' },
        { id: 'classes', title: '3. Clases y Variables de Instancia', explanation: 'Las variables de instancia empiezan con @ y los constructores se llaman "initialize".', example: 'class Gato\\n  def initialize(nombre)\\n    @nombre = nombre\\n  end\\nend', exercise: 'Crea una clase Jugador con initialize para @score. Agrega un método jugar que suba el score en 10.', hint: '@score = score_inicial, y def jugar @score += 10 end', solution: 'class Jugador\\n  def initialize(score)\\n    @score = score\\n  end\\n  def jugar\\n    @score += 10\\n  end\\nend' }
      ]
    }

    // FALLBACK GENÉRICO MEJORADO PARA OTROS LENGUAJES / TECNOLOGÍAS
    return [
      { id: 'vars', title: '1. Sintaxis Básica y Variables', explanation: "Entender cómo se declaran las variables es el paso 1 en " + techName + ". Todo lenguaje tiene un sistema de tipado (fuerte o dinámico) y reglas de mutabilidad (constantes vs variables).", example: '// Declaración de una variable mutable vs inmutable\\nvar mutable = 1;\\nconst inmutable = 2;', exercise: "En " + techName + ", declara una variable constante para almacenar la URL base de una API y otra variable para almacenar un contador de intentos.", hint: 'Usa la palabra reservada que indique inmutabilidad en este lenguaje para la URL, y otra para variables reasignables.', solution: '// Varía según lenguaje. Ej:\\nconst baseUrl = "api.com";\\nlet attempts = 0;' },
      { id: 'conds', title: '2. Estructuras de Control y Ramificación', explanation: 'El flujo del programa depende de evaluaciones lógicas. Condicionales (if, switch/match) permiten a la aplicación tomar decisiones dinámicas.', example: 'if (condicion_valida) {\\n  ejecutarRutaA();\\n} else {\\n  ejecutarRutaB();\\n}', exercise: 'Escribe un condicional que valide si un nivel de usuario es mayor a 10 y otorgue un permiso de administrador.', hint: 'Casi todos usan "if (condicion)". Revisa si necesita llaves {} o indentación.', solution: 'if (nivel > 10) { darPermiso(); }' },
      { id: 'loops', title: '3. Iteración y Bucles', explanation: 'Procesar conjuntos de datos requiere herramientas eficientes de iteración (For, While, o métodos funcionales).', example: 'for (elemento en lista) {\\n  procesar(elemento);\\n}', exercise: 'Construye un bucle iterativo que recorra del 1 al 5 imprimiendo los números.', hint: 'Busca sintaxis for i=1 to 5, o bucles clásicos de tipo C (i=1; i<=5; i++).', solution: 'for(i=1; i<=5; i++) { print(i); }' },
      { id: 'funcs', title: '4. Modularidad y Funciones', explanation: 'Las funciones encapsulan la lógica, haciéndola testeable y reutilizable. Entender los parámetros (argumentos) y los retornos (return) es esencial.', example: 'funcion calcularDescuento(precio, dto) {\\n  return precio - (precio * dto);\\n}', exercise: "Crea una función en " + techName + " que tome dos números, calcule su suma y la retorne al llamador.", hint: 'Busca las palabras func, def o function según el caso.', solution: 'function suma(a, b) { return a + b; }' },
      { id: 'data', title: '5. Estructuras de Datos Complejas', explanation: 'Para escenarios avanzados, agrupamos datos simples en estructuras más complejas como Listas, Arrays, Matrices, Diccionarios u Objetos.', example: 'lista = [1, 2, 3]\\ndiccionario = { "clave": "valor" }', exercise: 'Crea una estructura de datos que contenga una lista o arreglo de tus colores favoritos.', hint: 'Normalmente se utilizan corchetes [] para arrays y llaves {} para mapas/diccionarios.', solution: 'colores = ["rojo", "azul", "verde"];' }
    ];
  };`;

content = content.substring(0, curriculumStart) + massiveCurriculum + content.substring(curriculumEnd);

fs.writeFileSync(file, content, 'utf-8');
console.log('Done!');
