const fs = require('fs');
const path = 'app/dashboard/page.tsx';
let content = fs.readFileSync(path, 'utf8');

const startMarker = '  // CURRÍCULUM DINÁMICO PARA EL PLAYGROUND';
const endMarker = '  // LÓGICA DEL MINI-JUEGO';

const startIndex = content.indexOf(startMarker);
const endIndex = content.indexOf(endMarker);

if(startIndex !== -1 && endIndex !== -1) {
  const newCurriculum = `  // CURRÍCULUM DINÁMICO PARA EL PLAYGROUND
  const getCurriculum = (techName: string) => {
    const t = techName.toLowerCase();

    if (t.includes('python')) {
      return [
        { id: 'vars', title: '1. Variables e Indentación', explanation: 'En Python no usamos llaves {} para los bloques de código, usamos espacios (indentación). Las variables no necesitan declarar su tipo.', example: 'nombre = "Alex"\\nedad = 25\\n\\nif edad >= 18:\\n    print(nombre + " es mayor")', exercise: 'Crea una variable "puntuacion" con valor 100. Usa un if para imprimir "Ganaste" si es mayor a 50.', solution: 'puntuacion = 100\\nif puntuacion > 50:\\n    print("Ganaste")' },
        { id: 'lists', title: '2. Listas y Diccionarios', explanation: 'Python usa Listas (Arrays) y Diccionarios (Objetos clave-valor) de forma muy nativa y flexible.', example: 'juegos = ["Zelda", "Mario"]\\njuegos.append("Halo")\\n\\nperfil = {"nombre": "Alex", "nivel": 10}\\nprint(perfil["nivel"])', exercise: 'Crea un diccionario "usuario" con "alias" y "xp". Añade un juego nuevo a una lista de juegos.', solution: 'usuario = {"alias": "Dev", "xp": 50}\\njuegos = ["Tetris"]\\njuegos.append("Portal")\\nprint(usuario, juegos)' },
        { id: 'comp', title: '3. List Comprehensions', explanation: 'Una de las características más potentes de Python. Permite crear y filtrar listas en una sola línea de forma muy legible y rápida.', example: 'numeros = [1, 2, 3, 4, 5]\\ncuadrados = [n * n for n in numeros]\\npares = [n for n in numeros if n % 2 == 0]', exercise: 'Dada una lista de números del 1 al 5, crea una nueva lista solo con los impares usando comprehension.', solution: 'nums = [1, 2, 3, 4, 5]\\nimpares = [n for n in nums if n % 2 != 0]\\nprint(impares)' },
        { id: 'funcs', title: '4. Funciones (*args, **kwargs)', explanation: 'Las funciones se definen con "def". Además de parámetros normales, Python permite recibir un número variable de argumentos usando *args o **kwargs.', example: 'def saludar(*nombres):\\n    for n in nombres:\\n        print("Hola", n)\\n\\nsaludar("Ana", "Juan", "Pedro")', exercise: 'Crea una función "sumar_todos" que reciba *args y devuelva la suma de todos los números que se le pasen.', solution: 'def sumar_todos(*args):\\n    return sum(args)\\nprint(sumar_todos(1, 2, 3, 4))' },
        { id: 'oop', title: '5. POO y Clases', explanation: 'Python es multi-paradigma. En POO, usamos la palabra "class". Todos los métodos de instancia deben recibir "self" como primer parámetro.', example: 'class Perro:\\n    def __init__(self, nombre):\\n        self.nombre = nombre\\n\\n    def ladrar(self):\\n        print(self.nombre + " dice Guau!")\\n\\np = Perro("Rex")\\np.ladrar()', exercise: 'Crea una clase "Coche" con un constructor que reciba la marca. Añade un método "arrancar" que imprima "Brum brum".', solution: 'class Coche:\\n    def __init__(self, marca):\\n        self.marca = marca\\n    def arrancar(self):\\n        print("Brum brum")\\nc = Coche("Ford")\\nc.arrancar()' }
      ];
    }

    if (t.includes('react') || t.includes('next')) {
      return [
        { id: 'jsx', title: '1. Introducción a JSX', explanation: 'React usa JSX, una sintaxis que permite escribir HTML dentro de JavaScript/TypeScript. En lugar de "class", usamos "className".', example: 'export default function App() {\\n  const titulo = "React!";\\n  return (\\n    <div className="bg-dark">\\n      <h1>Hola {titulo}</h1>\\n    </div>\\n  );\\n}', exercise: 'Crea un componente "Boton" que devuelva un elemento <button> con el texto "Haz clic aquí" y un className "btn".', solution: 'export default function Boton() {\\n  return <button className="btn">Haz clic aquí</button>;\\n}' },
        { id: 'state', title: '2. Estado (useState)', explanation: 'Para que la interfaz reaccione a cambios, usamos el Hook "useState". Esto nos da una variable y una función para actualizarla y repintar la pantalla.', example: 'import { useState } from "react";\\n\\nexport default function Contador() {\\n  const [count, setCount] = useState(0);\\n  return <button onClick={() => setCount(count + 1)}>Cliqued {count}</button>;\\n}', exercise: 'Crea un componente con un estado "texto" inicializado vacío. Un botón que al hacer clic ponga "¡Actualizado!".', solution: 'import { useState } from "react";\\nexport default function App() {\\n  const [texto, setTexto] = useState("");\\n  return <button onClick={() => setTexto("¡Actualizado!")}>{texto || "Haz clic"}</button>;\\n}' },
        { id: 'props', title: '3. Propiedades (Props)', explanation: 'Las "props" son como los parámetros de una función, pero para componentes. Permiten pasar datos de un componente padre a un componente hijo.', example: 'function Saludo({ nombre }) {\\n  return <h2>Hola, {nombre}</h2>;\\n}\\n\\nexport default function App() {\\n  return <Saludo nombre="Alex" />;\\n}', exercise: 'Crea un componente "Tarjeta" que reciba "titulo" y "descripcion" como props y las pinte dentro de un div.', solution: 'function Tarjeta({ titulo, descripcion }) {\\n  return (\\n    <div>\\n      <h3>{titulo}</h3>\\n      <p>{descripcion}</p>\\n    </div>\\n  );\\n}\\nexport default function App() {\\n  return <Tarjeta titulo="T1" descripcion="Desc" />;\\n}' },
        { id: 'effect', title: '4. Efectos (useEffect)', explanation: 'El Hook "useEffect" permite ejecutar código "secundario", como pedir datos a una API, cuando el componente se carga o cuando un estado cambia.', example: 'import { useEffect, useState } from "react";\\n\\nexport default function App() {\\n  useEffect(() => {\\n    console.log("El componente se montó en pantalla");\\n  }, []);\\n  return <div>Hola</div>;\\n}', exercise: 'Crea un componente que cambie el title del documento (document.title) a "Cargado" cuando el componente se monte.', solution: 'import { useEffect } from "react";\\nexport default function App() {\\n  useEffect(() => {\\n    document.title = "Cargado";\\n  }, []);\\n  return <div>Hola</div>;\\n}' }
      ];
    }

    if (t.includes('javascript') || t.includes('typescript') || t.includes('node') || t.includes('express')) {
      return [
        { id: 'letconst', title: '1. Variables y Mutabilidad', explanation: 'En JS/TS moderno no usamos "var". Usamos "let" para variables que van a cambiar su valor y "const" para valores fijos que no serán reasignados.', example: 'const nombre = "Alex"; // Nunca cambiará\\nlet edad = 25; // Puede cambiar\\nedad = 26;\\n// nombre = "Juan"; // Daría error', exercise: 'Crea una constante "URL" y una variable "intentos". Asigna 0 a "intentos" y luego actualízalo a 1.', solution: 'const URL = "https://api.com";\\nlet intentos = 0;\\nintentos = 1;' },
        { id: 'arrow', title: '2. Funciones Flecha (Arrow)', explanation: 'Una sintaxis más corta para escribir funciones. Son muy usadas en callbacks y métodos de arrays porque no alteran el contexto de "this".', example: '// Función normal\\nfunction sumar(a, b) { return a + b; }\\n\\n// Arrow Function\\nconst sumarArrow = (a, b) => a + b;\\nconst saludar = nombre => console.log("Hola", nombre);', exercise: 'Convierte una función normal "multiplicar(x, y)" que retorna el producto, en una Arrow Function de una sola línea.', solution: 'const multiplicar = (x, y) => x * y;' },
        { id: 'arraymeth', title: '3. Array Methods (Map / Filter)', explanation: 'A diferencia de los bucles clásicos (for), JS tiene métodos funcionales increíbles para transformar listas de forma declarativa sin mutar el array original.', example: 'const nums = [1, 2, 3, 4];\\n\\n// Multiplicar todo por 2\\nconst dobles = nums.map(n => n * 2);\\n\\n// Filtrar solo los pares\\nconst pares = nums.filter(n => n % 2 === 0);', exercise: 'Dada una lista de palabras, usa .map() para transformarlas en mayúsculas (.toUpperCase()).', solution: 'const palabras = ["hola", "mundo"];\\nconst mayus = palabras.map(p => p.toUpperCase());\\nconsole.log(mayus);' },
        { id: 'destruct', title: '4. Desestructuración de Objetos', explanation: 'Extrae valores de arreglos o propiedades de objetos y los asigna a variables en una sola línea de código muy limpia.', example: 'const user = { name: "Alex", role: "Admin" };\\nconst { name, role } = user; // Extrae name y role\\n\\nconst rgb = [255, 0, 0];\\nconst [r, g, b] = rgb;', exercise: 'Crea un objeto "juego" con titulo y precio. Extrae ambas propiedades en variables usando desestructuración.', solution: 'const juego = { titulo: "Zelda", precio: 60 };\\nconst { titulo, precio } = juego;\\nconsole.log(titulo, precio);' },
        { id: 'async', title: '5. Promesas y Async / Await', explanation: 'JS no se bloquea al esperar tareas lentas. Usamos async/await para leer código asíncrono como si fuera secuencial.', example: 'async function obtenerDatos() {\\n  console.log("Cargando...");\\n  const res = await fetch("https://api.github.com/users/github");\\n  const data = await res.json();\\n  console.log(data.name);\\n}', exercise: 'Crea una función async "tarea" que use await con "fetch" para pedir datos a "https://api.github.com" y devuelva el JSON.', solution: 'async function tarea() {\\n  const res = await fetch("https://api.github.com");\\n  const data = await res.json();\\n  console.log(data);\\n}' }
      ];
    }

    if (t.includes('java') || t.includes('c#')) {
      let print = t.includes('c#') ? 'Console.WriteLine' : 'System.out.println';
      let title = t.includes('c#') ? 'C#' : 'Java';
      return [
        { id: 'types', title: '1. Tipado Fuerte y Clases Básicas', explanation: 'Estos lenguajes exigen que definas el TIPO exacto de cada variable. Además, todo el código DEBE vivir dentro de una Clase.', example: 'public class Main {\\n  public static void main(String[] args) {\\n    int edad = 25;\\n    String nombre = "Alex";\\n    ' + print + '("Hola " + nombre);\\n  }\\n}', exercise: 'Crea una variable entera (int) y un booleano (boolean/bool) dentro del método principal e imprímelos.', solution: 'int vidas = 3;\\nboolean activo = true;\\n' + print + '(vidas);\\n' + print + '(activo);' },
        { id: 'oop_constructors', title: '2. Clases y Constructores', explanation: 'Los objetos se instancian a partir de Clases. El Constructor es el método especial que se ejecuta automáticamente al usar "new".', example: 'class Perro {\\n  String nombre;\\n  \\n  // Constructor\\n  public Perro(String n) {\\n    this.nombre = n;\\n  }\\n}\\n// Uso:\\nPerro miPerro = new Perro("Rex");', exercise: 'Crea una clase "Coche" con propiedad "marca" de tipo String y un constructor que asigne dicha marca.', solution: 'class Coche {\\n  String marca;\\n  public Coche(String m) {\\n    this.marca = m;\\n  }\\n}' },
        { id: 'collections', title: '3. Listas y Colecciones', explanation: 'En vez de arrays estáticos fijos, se suelen usar colecciones dinámicas fuertemente tipadas provenientes de la librería estándar.', example: '// C#: List<String> nombres = new List<String>();\\n// Java: List<String> nombres = new ArrayList<>();\\nnombres.add("Alex");\\n' + print + '(nombres.get(0)); // En C# usarías nombres[0]', exercise: 'Crea una lista genérica para guardar números, añadele el número 10 y luego imprímelo.', solution: '// En Java:\\nList<Integer> nums = new ArrayList<>();\\nnums.add(10);\\n' + print + '(nums.get(0));' },
        { id: 'exceptions', title: '4. Control de Excepciones', explanation: 'Los errores en ejecución ("Runtime") se capturan con bloques Try/Catch para evitar que la aplicación colapse completamente y poder gestionarlos con gracia.', example: 'try {\\n  int calculo = 10 / 0;\\n} catch (Exception e) {\\n  ' + print + '("Hubo un error matemático");\\n}', exercise: 'Protege un código que intenta acceder al índice 5 de un array que solo tiene 2 posiciones. En el catch imprime un mensaje.', solution: 'try {\\n  int[] arr = {1, 2};\\n  int x = arr[5];\\n} catch (Exception e) {\\n  ' + print + '("Fuera de índice");\\n}' }
      ];
    }

    if (t.includes('c++') || t.includes('cpp')) {
      return [
        { id: 'headers', title: '1. Includes y main()', explanation: 'En C++ debemos incluir las librerías necesarias con #include (como iostream). El punto de entrada del programa siempre es la función int main().', example: '#include <iostream>\\nusing namespace std;\\n\\nint main() {\\n  cout << "Hola Mundo" << endl;\\n  return 0;\\n}', exercise: 'Escribe la estructura básica de un archivo C++ que devuelva 0 y que imprima tu nombre por consola.', solution: '#include <iostream>\\nusing namespace std;\\nint main() {\\n  cout << "TuNombre" << endl;\\n  return 0;\\n}' },
        { id: 'pointers', title: '2. Punteros y Memoria Manual', explanation: 'C++ te da control total y directo de la memoria. Un puntero (*) es una variable especial que no guarda un valor común, sino la DIRECCIÓN de memoria de otra variable.', example: 'int vida = 100;\\nint* ptrVida = &vida; // "&" obtiene la dirección de "vida"\\n\\ncout << "Valor: " << *ptrVida << endl;\\ncout << "Dirección: " << ptrVida << endl;', exercise: 'Declara una variable int "puntos". Crea un puntero que apunte a ella e imprime su valor usando solo el puntero.', solution: 'int puntos = 50;\\nint* ptr = &puntos;\\ncout << *ptr << endl;' },
        { id: 'vectors', title: '3. Librería de Plantillas Estándar (std::vector)', explanation: 'Aunque C++ tiene arrays crudos heredados de C, en el desarrollo C++ moderno se utilizan Vectores, que son arrays dinámicos y automáticos de la STL.', example: '#include <vector>\\n// ...\\nvector<int> nums;\\nnums.push_back(10);\\nnums.push_back(20);\\ncout << nums.size() << endl;', exercise: 'Crea un vector de enteros, añade tres números mediante push_back y usa un bucle for tradicional para iterar sobre ellos.', solution: 'vector<int> v;\\nv.push_back(1);\\nv.push_back(2);\\nfor(int i=0; i<v.size(); i++) {\\n  cout << v[i] << endl;\\n}' },
        { id: 'oop_cpp', title: '4. POO y Modificadores de Acceso', explanation: 'En C++ definimos clases con especificadores de acceso explícitos (public, private) aplicados a bloques enteros de atributos y métodos.', example: 'class Enemigo {\\nprivate:\\n  int hp;\\npublic:\\n  Enemigo(int vida) { hp = vida; }\\n  void recibirDano() { hp -= 10; }\\n};\\n\\nint main() {\\n  Enemigo orco(100);\\n}', exercise: 'Crea una clase Jugador con una variable privada "mana" y un constructor público que asigne esa variable.', solution: 'class Jugador {\\nprivate:\\n  int mana;\\npublic:\\n  Jugador(int m) {\\n    mana = m;\\n  }\\n};' }
      ];
    }

    // FALLBACK GENÉRICO PARA OTROS LENGUAJES / TECNOLOGÍAS
    return [
      { id: 'vars', title: '1. Variables y Fundamentos', explanation: \`Aprender \${techName} comienza por entender cómo se guardan los datos. Todo lenguaje tiene variables (cajas de datos en memoria) y tipos básicos (Textos, Números, Booleanos).\`, example: '// Ejemplo genérico\\nnombre = "Alex"\\nedad = 25', exercise: 'Crea dos variables: una de texto y otra numérica, y busca cómo imprimirlas en consola.', solution: '// La solución dependerá del lenguaje específico que estés probando\\nnombre = "Test";\\nvalor = 1;\\nprint/console.log(nombre, valor);' },
      { id: 'conds', title: '2. Condicionales y Lógica de Flujo', explanation: 'Los programas toman decisiones evaluando condiciones booleanas. Si ocurre un evento o se cumple una regla, ejecuta algo, si no, ejecuta otra cosa.', example: 'if (edad >= 18) {\\n  mostrar("Permitido");\\n} else {\\n  mostrar("Denegado");\\n}', exercise: 'Escribe un bloque condicional que evalúe si un número es mayor a 10.', solution: 'if (num > 10) { print("Mayor"); } else { print("Menor"); }' },
      { id: 'loops', title: '3. Repetición Estructurada (Bucles)', explanation: 'Para no tener que repetir el mismo código mil veces a mano, usamos bucles (For, While, Do-While) que iteran sobre colecciones o ejecutan instrucciones N veces.', example: 'for i = 1 to 5 {\\n  imprimir(i)\\n}', exercise: 'Crea un bucle que se repita 3 veces imprimiendo un mensaje en consola.', solution: 'for (i=0; i<3; i++) { print("Hola"); }' },
      { id: 'funcs', title: '4. Modularidad y Funciones', explanation: 'Cuando el código crece demasiado, lo dividimos y empaquetamos en funciones reutilizables que pueden recibir parámetros y retornar nuevos valores procesados.', example: 'funcion sumar(a, b) {\\n  return a + b;\\n}\\ntotal = sumar(5, 5);', exercise: 'Crea una función llamada "multiplicar" que reciba dos parámetros y retorne su producto.', solution: 'function multiplicar(a, b) { return a * b; }' },
      { id: 'data', title: '5. Estructuras de Datos Complejas', explanation: 'Para escenarios avanzados, agrupamos datos simples en estructuras más complejas como Listas, Arrays, Matrices, Diccionarios u Objetos.', example: 'lista = [1, 2, 3]\\ndiccionario = { "clave": "valor" }', exercise: 'Crea una estructura de datos que contenga una lista o arreglo de tus colores favoritos.', solution: 'colores = ["rojo", "azul", "verde"];' }
    ];
  };\n\n`;

  const before = content.substring(0, startIndex);
  const after = content.substring(endIndex);
  content = before + newCurriculum + after;
  fs.writeFileSync(path, content, 'utf8');
}
